# Generated by Django 4.2.26 on 2026-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_uce_model_reference_group_notnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ucemodel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
