# Generated by Django 4.2.26 on 2026-04-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_ucemodel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch_job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
