# Generated by Django 4.2.26 on 2026-04-10 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0010_job_batch_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projection_id', models.UUIDField(db_index=True)),
                ('job_id', models.UUIDField(db_index=True)),
                ('reference_id', models.CharField(max_length=100)),
                ('reference_title', models.CharField(max_length=255)),
                ('event', models.CharField(choices=[('created', 'Created'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(db_index=True)),
                ('event', models.CharField(choices=[('created', 'Created'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('cell_count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
