# Generated by Django 4.2.26 on 2026-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_projection_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
