# Generated by Django 4.2.26 on 2026-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_documentchunk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentchunk',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
