# Generated by Django 4.2.26 on 2026-05-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_sharetoken'),
        ('jobs', '0014_alter_documentchunk_id'),
    ]

    operations = [
    ]
