# Generated by Django 4.2.26 on 2026-06-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_merge_0013_sharetoken_0014_alter_documentchunk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharetoken',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
