# Generated by Django 4.2.26 on 2026-08-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email_on_complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
